# Generated by Django 4.2 on 2025-01-07 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('countryResidence', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tables.countryresidence')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tables.gender')),
                ('levelStudy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tables.levelstudy')),
                ('professionalTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='tables.professionaltitle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ext', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
