# Generated by Django 4.2 on 2025-01-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ext',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
