# Generated by Django 4.2 on 2025-02-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0002_alter_ext_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='user_ext.ext')),
            ],
        ),
    ]
