# Generated by Django 4.2 on 2025-02-13 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_ext', '0003_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='training',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='institute',
            field=models.CharField(default='Universidad Central del Ecuador', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='location',
            field=models.CharField(default='Santa Clara', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='startDate',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='studentTraining',
            field=models.CharField(default='Tercer Nivel', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
                ('ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='user_ext.ext')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('range', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user_ext.ext')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='user_ext.ext')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('range', models.IntegerField()),
                ('ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='user_ext.ext')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=255)),
                ('ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbys', to='user_ext.ext')),
            ],
        ),
    ]
