# Generated by Django 4.2 on 2025-02-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_ext', '0003_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('subtitle2', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('director', models.CharField(max_length=225)),
                ('file', models.FileField(upload_to='certificate')),
                ('ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certify', to='user_ext.ext')),
            ],
        ),
    ]
