# Generated by Django 4.2 on 2025-01-07 22:13

from django.db import migrations, models
from utils.migrate import ImportDataBetter


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def LoadGender(apps, schema_editor):
        jdata = [
        {'name': 'Femenino', 'code': 'Fe'},
        {'name': 'Masculino', 'code': 'Ma'},
        {'name': 'Otro', 'code': 'Ot'},
    ]
        Gender = apps.get_model('tables', 'Gender')
        Gender.objects.bulk_create(Gender(**data) for data in jdata)


    def LoadLevelStudy(apps, schema_editor):
        jdata = [
        {'name': 'Primaria', 'code': 'Pr'},
        {'name': 'Secundaria', 'code': 'Se'},
        {'name': 'Bachillerato', 'code': 'Ba'},
        {'name': 'Licenciatura', 'code': 'Li'},
        {'name': 'Maestría', 'code': 'Ma'},
        {'name': 'Doctorado', 'code': 'Do'},
        {'name': 'Otro', 'code': 'Ot'},
    ]
        LevelStudy = apps.get_model('tables', 'LevelStudy')
        LevelStudy.objects.bulk_create(LevelStudy(**data) for data in jdata)

    def LoadCountryResidence(apps, schema_editor):
        jdata = ImportDataBetter('tables', 'Country')
        CountryResidence = apps.get_model('tables', 'CountryResidence')
        CountryResidence.objects.bulk_create(CountryResidence(**data) for data in jdata)


    def LoadProfessionalTitle(apps, schema_editor):
        jdata = ImportDataBetter('tables', 'profesiones')
        ProfessionalTitle = apps.get_model('tables', 'ProfessionalTitle')
        ProfessionalTitle.objects.bulk_create(ProfessionalTitle(**data) for data in jdata)

    operations = [
        migrations.CreateModel(
            name='CountryResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Países de residencia',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='LevelStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Niveles de estudio',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Títulos profesionales',
            },
        ),

        migrations.RunPython(LoadGender),
        migrations.RunPython(LoadLevelStudy),
        migrations.RunPython(LoadCountryResidence),
        migrations.RunPython(LoadProfessionalTitle),
    ]

